import React, { useEffect } from 'react';
import './App.css';
import Textform from './components/Textform';

function App() {
  useEffect(() => {
    speak("Welcome !");
  }, []);

  // Function to speak the given text
  const speak = (text) => {
    const synth = window.speechSynthesis;
    const utterance = new SpeechSynthesisUtterance(text);
    
    // You can specify voice options here
    utterance.voice = getVoiceByName("Google English Female"); // Example of a female voice
    
    synth.speak(utterance);
  };

  // Function to get a voice by name
  const getVoiceByName = (name) => {
    const synth = window.speechSynthesis;
    const voices = synth.getVoices();
    return voices.find(voice => voice.name === name);
  };

  return (
    <div className="container my-3">
      <h1 className="text-center mb-4" style={{ color: '#007bff' }}>Text Editor App</h1>
      <h5 className="text-muted text-center">Generated by Janita</h5>
      <Textform/>
    </div>
  );
}

export default App;
